### ISSUE TITLE
Document The Monitoring PC

### ISSUE THREAD

**Issue by ron-popov** [Rogozin-high-school/sat_documentation#1]
Once Setting up the PC is done I think we should document how it works as well (os, programs installed, etc), and how it connects and communicates with all of the experiment's components.

**Comment by yotam180** [comment]
I'll make a concatenated document soon to document it all (unless you had a better idea).

**Comment by yotam180** [comment]
Moved to a Google Document.

**Comment by ron-popov** [comment]
Is there a link to the google document in this github repo ? and could you make it public so that anyone who has the link to the document could view it ?

**Comment by yotam180** [comment]
Yes. Definitely.
You can look at it [here](https://docs.google.com/document/d/1bNRA-2Ku-cKybcSwfgLaPY76-h52f2U4eMDIJ_poN6k/edit?usp=sharing).
